default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hack_development
test:
  <<: *default
  database: hack_test

production:
  <<: *default
  database: hack_prod
  username: developer
  password: 45685293
